In [1]:
import numpy as np

In [3]:
ones = np.ones((6,6), dtype='int32')
ones[1:-1, 1:-1] = 0
ones

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

In [5]:
arr_permutatuion = np.random.permutation([10, 20, 30, 40, 50])
gen = np.random.permutation(arr_permutatuion)
gen

array([20, 40, 30, 10, 50])

In [9]:
random_dist = np.random.normal(0,1, (2,3))
random_dist

array([[-0.63970927, -0.35612571, -0.57452572],
       [-0.52883718,  1.30186835,  0.96120275]])

In [11]:
web_hits = np.random.poisson(lam=100, size=30)
web_hits

array([101, 101,  91,  91,  96, 109,  89, 129, 101, 103,  96,  87,  88,
       111,  89,  98, 103, 116,  95, 116,  90, 115,  98, 104, 101, 108,
       110,  87,  89, 120])

In [13]:
average_hits = 20
days=7
hours=24
web_hits_7 = np.random.poisson(lam=average_hits, size=(days,hours))
web_hits_7

array([[23, 22, 19, 24, 20, 22, 22, 21, 14, 18, 18, 22, 26, 26, 16, 21,
        15, 22, 29, 27, 21, 14, 19, 25],
       [18, 21, 19, 23, 27, 23, 24, 18, 22, 13, 23, 16, 13, 23, 14, 16,
        17, 24, 24, 23, 22, 17, 19, 16],
       [16, 12, 21, 23, 24, 26, 17, 19, 13, 23, 22, 19, 23, 18, 18, 26,
        18, 27, 30, 22, 17, 14, 24, 24],
       [15, 19, 18, 16, 23, 16, 18, 23, 20, 31, 17, 16, 20, 18, 16, 19,
        12, 18, 24, 20, 23, 15, 24, 17],
       [18, 22, 16, 11, 16, 31, 13, 18, 15, 24, 10, 22, 20, 28, 24, 17,
        18, 20, 30, 18, 15, 18, 20, 23],
       [24, 16, 19, 23, 18, 16, 18, 14, 21, 20, 25, 19, 26, 18, 29, 22,
        30, 27, 16, 18, 24, 24, 15, 25],
       [21, 22, 31, 20, 16, 15, 22, 23, 17, 16, 19, 18, 30, 12, 18, 18,
        23, 21, 22, 24, 21, 25, 23, 18]])

In [15]:
average_day = np.average(web_hits_7,axis=1,keepdims=True)
average_day

array([[21.08333333],
       [19.79166667],
       [20.66666667],
       [19.08333333],
       [19.45833333],
       [21.125     ],
       [20.625     ]])

In [17]:
sum_day = np.sum(web_hits_7, axis=1, keepdims=True)
sum_day

array([[506],
       [475],
       [496],
       [458],
       [467],
       [507],
       [495]])

In [19]:
for i in web_hits_7:
    print(f"Daily average: {np.average(i)}")

for i in web_hits_7:
    print(f"Daily sum: {np.sum(i)}")

Daily average: 21.083333333333332
Daily average: 19.791666666666668
Daily average: 20.666666666666668
Daily average: 19.083333333333332
Daily average: 19.458333333333332
Daily average: 21.125
Daily average: 20.625
Daily sum: 506
Daily sum: 475
Daily sum: 496
Daily sum: 458
Daily sum: 467
Daily sum: 507
Daily sum: 495
